;
; Driver Installer Section (For DrvInst) 
;
; Copyright (c) 2005-2011 RICOH COMPANY, LTD
; All Rights Reserved
;

[DrvInst]
DrvInst= Gestetner MP 301 PCL 5e,infotec MP 301 PCL 5e,LANIER MP 301 PCL 5e,NRG MP 301 PCL 5e,RICOH Aficio MP 301 PCL 5e,SAVIN MP 301 PCL 5e
Comment="PCL 5e Driver (For Windows)"
VendorSetup= 
NoCheckFiles=
DriverType=PCL5e
Version=3
IniFileName=RPCL.ini,11
ScenarioInstallOK=ON
RConfigFileOSVersion=3
DriverVersion=1.0.0.0
IniFileSupport=2
