;
; Driver Installer Section (For DrvInst)
;
; Copyright (c) 1998-2014 RICOH COMPANY, LTD
; All Rights Reserved
;

[DrvInst]
DrvInst=RICOH Aficio MP C2800 PCL 6,RICOH Aficio MP C3300 PCL 6
Comment="PCL 6 Driver (Windows XP/Server 2003/Vista 64-bit)"
VendorSetup=
NoCheckFiles=
DriverType=PCL6
Version=3
IniFileName=RPCL.ini,11
ScenarioInstallOK=ON
RConfigFileOSVersion=3
DriverVersion=1.7.0.0
IniFileSupport=3
RCFFormatVersion=1.0
RCFHandling=1
UserCodeOK=ON
Platform=NTamd64
